type WordList = {
  word: string;
  hint: string;
};

const wordList: Array<WordList> = [
  { word: "viagem", hint: "Exploração de novos lugares." },
  { word: "café", hint: "Bebida quente e estimulante." },
  { word: "montanha", hint: "Elevação natural da terra." },
  { word: "rima", hint: "Palavras com sons semelhantes." },
  { word: "pintura", hint: "Arte de criar imagens visuais." },
  { word: "coração", hint: "Órgão que bombeia sangue." },
  { word: "paraíso", hint: "Lugar perfeito e harmonioso." },
  { word: "família", hint: "Parentes próximos e queridos." },
  { word: "escola", hint: "Local de aprendizado." },
  { word: "dinheiro", hint: "Meio de troca e pagamento." },
  { word: "folha", hint: "Parte verde de uma planta." },
  { word: "tempo", hint: "A medida das horas." },
  { word: "fogo", hint: "Uma forma de energia." },
  { word: "arco-íris", hint: "Uma mistura colorida no céu." },
  { word: "cidade", hint: "Grande área urbana." },
  { word: "amor", hint: "Sentimento profundo de afeição." },
  { word: "livro", hint: "Uma coleção de histórias escritas." },
  { word: "felicidade", hint: "Estado de alegria e contentamento." },
  { word: "computador", hint: "Máquina que processa informações." },
  { word: "chuva", hint: "Gotas de água que caem do céu." },
  { word: "praia", hint: "Litoral com areia e água do mar." },
  { word: "restaurante", hint: "Local para refeições." },
  { word: "sorriso", hint: "Expressão facial de alegria." },
  { word: "mundo", hint: "O planeta Terra." },
  { word: "cachorro", hint: "Animal de estimação leal." },
  { word: "guitarra", hint: "Instrumento musical de cordas." },
  { word: "amarelo", hint: "Cor brilhante e quente." },
  { word: "fotografia", hint: "Arte de capturar imagens." },
  { word: "amigo", hint: "Pessoa próxima e confiável." },
  { word: "coração", hint: "Órgão que bombeia sangue." },
  { word: "viagem", hint: "Exploração de novos lugares." },
  { word: "café", hint: "Bebida quente e estimulante." },
  { word: "montanha", hint: "Elevação natural da terra." },
  { word: "rima", hint: "Palavras com sons semelhantes." },
  { word: "pintura", hint: "Arte de criar imagens visuais." },
  { word: "coração", hint: "Órgão que bombeia sangue." },
  { word: "paraíso", hint: "Lugar perfeito e harmonioso." },
  { word: "família", hint: "Parentes próximos e queridos." },
  { word: "escola", hint: "Local de aprendizado." },
  { word: "dinheiro", hint: "Meio de troca e pagamento." },
  { word: "folha", hint: "Parte verde de uma planta." },
  { word: "tempo", hint: "A medida das horas." },
  { word: "fogo", hint: "Uma forma de energia." },
  { word: "arco-íris", hint: "Uma mistura colorida no céu." },
  { word: "cidade", hint: "Grande área urbana." },
  { word: "amor", hint: "Sentimento profundo de afeição." },
  { word: "livro", hint: "Uma coleção de histórias escritas." },
  { word: "felicidade", hint: "Estado de alegria e contentamento." },
  { word: "computador", hint: "Máquina que processa informações." },
  { word: "chuva", hint: "Gotas de água que caem do céu." },
  { word: "praia", hint: "Litoral com areia e água do mar." },
  { word: "restaurante", hint: "Local para refeições." },
  { word: "sorriso", hint: "Expressão facial de alegria." },
  { word: "mundo", hint: "O planeta Terra." },
  { word: "cachorro", hint: "Animal de estimação leal." },
  { word: "guitarra", hint: "Instrumento musical de cordas." },
  { word: "amarelo", hint: "Cor brilhante e quente." },
  { word: "fotografia", hint: "Arte de capturar imagens." },
  { word: "amigo", hint: "Pessoa próxima e confiável." },
  { word: "coração", hint: "Órgão que bombeia sangue." },
  { word: "viagem", hint: "Exploração de novos lugares." },
  { word: "café", hint: "Bebida quente e estimulante." },
  { word: "montanha", hint: "Elevação natural da terra." },
  { word: "rima", hint: "Palavras com sons semelhantes." },
  { word: "pintura", hint: "Arte de criar imagens visuais." },
  { word: "computador", hint: "Máquina que processa informações." },
  { word: "chuva", hint: "Gotas de água que caem do céu." },
  { word: "paraíso", hint: "Lugar perfeito e harmonioso." },
  { word: "família", hint: "Parentes próximos e queridos." },
  { word: "escola", hint: "Local de aprendizado." },
  { word: "dinheiro", hint: "Meio de troca e pagamento." },
  { word: "folha", hint: "Parte verde de uma planta." },
  { word: "tempo", hint: "A medida das horas." },
  { word: "fogo", hint: "Uma forma de energia." },
  { word: "arco-íris", hint: "Uma mistura colorida no céu." },
  { word: "cidade", hint: "Grande área urbana." },
  { word: "amor", hint: "Sentimento profundo de afeição." },
  { word: "livro", hint: "Uma coleção de histórias escritas." },
  { word: "felicidade", hint: "Estado de alegria e contentamento." },
  { word: "computador", hint: "Máquina que processa informações." },
  { word: "chuva", hint: "Gotas de água que caem do céu." },
  { word: "praia", hint: "Litoral com areia e água do mar." },
  { word: "restaurante", hint: "Local para refeições." },
  { word: "sorriso", hint: "Expressão facial de alegria." },
  { word: "mundo", hint: "O planeta Terra." },
  { word: "cachorro", hint: "Animal de estimação leal." },
  { word: "guitarra", hint: "Instrumento musical de cordas." },
  { word: "amarelo", hint: "Cor brilhante e quente." },
  { word: "fotografia", hint: "Arte de capturar imagens." },
  { word: "amigo", hint: "Pessoa próxima e confiável." },
];

export default wordList;
